<a href="https://colab.research.google.com/github/HarryAI-6748/trendpulse-Harkirat/blob/main/task2_data_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the required libraries

In [ ]:
import requests
import json
import pandas as pd

Loading the JSON file from the data/ folder into a Pandas DataFrame

In [ ]:
df = pd.read_json('/content/data/trends_20260409.json')
df

,post_id,category,author,num_comments,score,title,collected_at
0,47619879,None,uticus,70.0,83,U.S. is burning through Tomahawk cruise missil...,2026-04-09 11:38:49
1,47620933,technology,notem,36.0,59,Memo: A language that remembers only the last ...,2026-04-09 11:38:49
2,47621133,None,benwerd,1.0,9,Design for the Roller Coaster,2026-04-09 11:38:49
3,47621438,None,codingmoh,61.0,153,Show HN: Made a little Artemis II tracker,2026-04-09 11:38:49
4,47621448,None,OhMeadhbh,30.0,79,A Few Good Magazines From the 70s and 80s,2026-04-09 11:38:49
...,...,...,...,...,...,...,...
495,47701100,None,nixass,12.0,38,Creating the Futurescape for the Fifth Element...,2026-04-09 11:38:49
496,47701233,None,sixhobbits,85.0,105,Claude mixes up who said what and that's not OK,2026-04-09 11:38:49
497,47701433,None,robtherobber,5.0,14,America Has Lost the Arab World,2026-04-09 11:38:49
498,47701572,None,eigenspace,3.0,16,"Wit, unker, Git: The lost medieval pronouns of...",2026-04-09 11:38:49
499,47701971,technology,gpi,0.0,4,AI and remote work is a disaster for junior so...,2026-04-09 11:38:49

Printing how many rows were loaded

In [ ]:
df.shape[0]

500

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   post_id       500 non-null    int64
 1   category      75 non-null     object
 2   author        500 non-null    object
 3   num_comments  499 non-null    float64
 4   score         500 non-null    int64
 5   title         500 non-null    object
 6   collected_at  500 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 31.2+ KB

Removing any rows with the same post_id

In [ ]:
df_dup = df.drop_duplicates(subset=['post_id'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   post_id       500 non-null    int64
 1   category      75 non-null     object
 2   author        500 non-null    object
 3   num_comments  499 non-null    float64
 4   score         500 non-null    int64
 5   title         500 non-null    object
 6   collected_at  500 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 31.2+ KB

Drop rows where post_id, title, or score is missing

In [ ]:
df[['title', 'post_id', 'score']].isnull()# No missing
df_null = df.dropna(subset=['title', 'post_id', 'score'])
df_null.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   post_id       500 non-null    int64
 1   category      75 non-null     object
 2   author        500 non-null    object
 3   num_comments  499 non-null    float64
 4   score         500 non-null    int64
 5   title         500 non-null    object
 6   collected_at  500 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 31.2+ KB

Make sure that score and num_comments are integers

In [ ]:
df['score'] = df[['score']].astype(int)
df

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   post_id       500 non-null    int64
 1   category      75 non-null     object
 2   author        500 non-null    object
 3   num_comments  499 non-null    float64
 4   score         500 non-null    int64
 5   title         500 non-null    object
 6   collected_at  500 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 31.2+ KB

In [ ]:
df['num_comments'].median()

23.0

In [ ]:
df['num_comments'].fillna(df['num_comments'].median(), inplace = True)

/tmp/ipykernel_2727/1564605543.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['num_comments'].fillna(df['num_comments'].median(), inplace = True)

In [ ]:
df['num_comments'] = df[['num_comments']].astype(int)

<bound method DataFrame.info of       post_id    category        author  num_comments  score  \
0    47619879        None        uticus            70     83
1    47620933  technology         notem            36     59
2    47621133        None       benwerd             1      9
3    47621438        None     codingmoh            61    153
4    47621448        None     OhMeadhbh            30     79
..        ...         ...           ...           ...    ...
495  47701100        None        nixass            12     38
496  47701233        None    sixhobbits            85    105
497  47701433        None  robtherobber             5     14
498  47701572        None    eigenspace             3     16
499  47701971  technology           gpi             0      4

                                                 title        collected_at
0    U.S. is burning through Tomahawk cruise missil... 2026-04-09 11:38:49
1    Memo: A language that remembers only the last ... 2026-04-09 11:38:49
2                        Design for the Roller Coaster 2026-04-09 11:38:49
3            Show HN: Made a little Artemis II tracker 2026-04-09 11:38:49
4            A Few Good Magazines From the 70s and 80s 2026-04-09 11:38:49
..                                                 ...                 ...
495  Creating the Futurescape for the Fifth Element... 2026-04-09 11:38:49
496    Claude mixes up who said what and that's not OK 2026-04-09 11:38:49
497                    America Has Lost the Arab World 2026-04-09 11:38:49
498  Wit, unker, Git: The lost medieval pronouns of... 2026-04-09 11:38:49
499  AI and remote work is a disaster for junior so... 2026-04-09 11:38:49

[500 rows x 7 columns]>

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   post_id       500 non-null    int64
 1   category      75 non-null     object
 2   author        500 non-null    object
 3   num_comments  500 non-null    int64
 4   score         500 non-null    int64
 5   title         500 non-null    object
 6   collected_at  500 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 31.2+ KB

 Removing stories where score is less than 5

In [ ]:
df_high = df[df['score'] > 5]
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   post_id       500 non-null    int64
 1   category      75 non-null     object
 2   author        500 non-null    object
 3   num_comments  499 non-null    float64
 4   score         500 non-null    int64
 5   title         500 non-null    object
 6   collected_at  500 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 31.2+ KB

In [ ]:
df_high = df.dropna(subset=['category'])

In [ ]:
df_high.info()

<class 'pandas.core.frame.DataFrame'>
Index: 75 entries, 1 to 499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   post_id       75 non-null     int64
 1   category      75 non-null     object
 2   author        75 non-null     object
 3   num_comments  75 non-null     float64
 4   score         75 non-null     int64
 5   title         75 non-null     object
 6   collected_at  75 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 4.7+ KB

Striping extra spaces from the title column

In [ ]:
df_high['title'] = df_high['title'].str.replace(' ', '')
df_high

/tmp/ipykernel_2727/2466822929.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_high['title'] = df_high['title'].str.replace(' ', '')

,post_id,category,author,num_comments,score,title,collected_at
1,47620933,technology,notem,36.0,59,Memo:Alanguagethatremembersonlythelast12lineso...,2026-04-09 11:38:49
11,47624645,technology,franze,157.0,738,ShowHN:Apfel–ThefreeAIalreadyonyourMac,2026-04-09 11:38:49
21,47627217,science,romes,127.0,218,Runningoutofdiskspaceinproduction,2026-04-09 11:38:49
23,47627419,worldnews,cmitsakis,12.0,47,TheAxiossupplychainattackusedindividuallytarge...,2026-04-09 11:38:49
33,47629485,science,thejash,54.0,67,Acasestudyintestingwith100+Claudeagentsinparallel,2026-04-09 11:38:49
...,...,...,...,...,...,...,...
475,47699105,technology,airobus,3.0,5,ShowHN:ImagetoMusicAI–TurnAnyPhotointoanOrigin...,2026-04-09 11:38:49
483,47699814,technology,ankitg12,11.0,48,ProcessManagerforAutonomousAIAgents,2026-04-09 11:38:49
488,47700460,technology,meander_water,66.0,52,AskHN:Whatareyoubuildingthat'snotAIrelated?,2026-04-09 11:38:49
493,47701013,technology,doener,0.0,9,LargestDutchpensionfundcutstieswithcontroversi...,2026-04-09 11:38:49
499,47701971,technology,gpi,0.0,4,AIandremoteworkisadisasterforjuniorsoftwareeng...,2026-04-09 11:38:49

Saving file to CSV in data folder

In [ ]:
df_high.to_csv('data/trends_clean.csv')

In [ ]:
print(
    f"Loaded {len(df)} stories from /content/data/trends_20260409.json","\n\n",
    f"After removing duplicates: {len(df_dup)}","\n",
    f"After removing nulls: {len(df_null)}","\n",
    f"After removing low scores: {len(df_high)}","\n\n",
    f"Saved {len(df_high)} rows to data/trends_clean.csv",

    "Stories per category:","\n\n"

    f"technology: {len(df_high[df_high['category'] == 'technology'])}","\n",
    f"worldnews: {len(df_high[df_high['category'] == 'worldnews'])}","\n",
    f"entertainment: {len(df_high[df_high['category'] == 'entertainment'])}","\n",
    f"sports: {len(df_high[df_high['category'] == 'sports'])}","\n",
    f"science: {len(df_high[df_high['category'] == 'science'])}",


)

Loaded 500 stories from /content/data/trends_20260409.json

 After removing duplicates: 500
 After removing nulls: 500
 After removing low scores: 75

 Saved 75 rows to data/trends_clean.csv Stories per category:

technology: 60
 worldnews: 3
 entertainment: 5
 sports: 2
 science: 5