<a href="https://colab.research.google.com/github/HarryAI-6748/trendpulse-Harkirat/blob/main/task3_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the required libraries

In [ ]:
import json
import pandas as pd
import numpy as np

Loading data/trends_clean.csv into a Pandas DataFrame

In [ ]:
df = pd.read_csv('/content/data/trends_clean.csv')
df = df.drop(df.columns[0], axis=1)
df

,post_id,category,author,num_comments,score,title,collected_at
0,47620933,technology,notem,36.0,59,Memo:Alanguagethatremembersonlythelast12lineso...,2026-04-09 11:38:49
1,47624645,technology,franze,157.0,738,ShowHN:Apfel–ThefreeAIalreadyonyourMac,2026-04-09 11:38:49
2,47627217,science,romes,127.0,218,Runningoutofdiskspaceinproduction,2026-04-09 11:38:49
3,47627419,worldnews,cmitsakis,12.0,47,TheAxiossupplychainattackusedindividuallytarge...,2026-04-09 11:38:49
4,47629485,science,thejash,54.0,67,Acasestudyintestingwith100+Claudeagentsinparallel,2026-04-09 11:38:49
...,...,...,...,...,...,...,...
70,47699105,technology,airobus,3.0,5,ShowHN:ImagetoMusicAI–TurnAnyPhotointoanOrigin...,2026-04-09 11:38:49
71,47699814,technology,ankitg12,11.0,48,ProcessManagerforAutonomousAIAgents,2026-04-09 11:38:49
72,47700460,technology,meander_water,66.0,52,AskHN:Whatareyoubuildingthat'snotAIrelated?,2026-04-09 11:38:49
73,47701013,technology,doener,0.0,9,LargestDutchpensionfundcutstieswithcontroversi...,2026-04-09 11:38:49
74,47701971,technology,gpi,0.0,4,AIandremoteworkisadisasterforjuniorsoftwareeng...,2026-04-09 11:38:49

Printing the first 5 rows

In [ ]:
head = df.head(5)
df.head(5)

,post_id,category,author,num_comments,score,title,collected_at
0,47620933,technology,notem,36.0,59,Memo:Alanguagethatremembersonlythelast12lineso...,2026-04-09 11:38:49
1,47624645,technology,franze,157.0,738,ShowHN:Apfel–ThefreeAIalreadyonyourMac,2026-04-09 11:38:49
2,47627217,science,romes,127.0,218,Runningoutofdiskspaceinproduction,2026-04-09 11:38:49
3,47627419,worldnews,cmitsakis,12.0,47,TheAxiossupplychainattackusedindividuallytarge...,2026-04-09 11:38:49
4,47629485,science,thejash,54.0,67,Acasestudyintestingwith100+Claudeagentsinparallel,2026-04-09 11:38:49

Printing the shape of the DataFrame (rows and columns)

In [ ]:
shape = df.shape#rows, columns

Printing the average score and average num_comments across all stories

In [ ]:
x = df[['score', 'num_comments']].mean().reset_index()
x.columns = ['Parameter', 'Avg']
x

#

      Parameter         Avg
0         score  195.560000
1  num_comments   79.626667

What is the mean, median, and standard deviation of score?

In [ ]:
df['score'].agg(['mean', 'median', 'std'])

mean      195.56000
median     57.00000
std       348.99788
Name: score, dtype: float64

What is the highest score and lowest score?

In [ ]:
df['score'].max()

2072

In [ ]:
df['score'].min()

3

Which story has the most comments? Print its title and comment count.

In [ ]:
num = df['num_comments'].max()

In [ ]:
mcomm = df[df['num_comments'] == df['num_comments'].max()]['title'].to_string(index=False, header = False)
#print(df[df['num_comments'] == df['num_comments'].max()]['title'].to_string(index=False, header = False))
mcomm
#

'ProjectGlasswing:Securingcriticalsoftwareforthe...'

Adding two new columns to the DataFrame

In [ ]:
df['num_comments'] / (df['score'] + 1)

0     0.600000
1     0.212449
2     0.579909
3     0.250000
4     0.794118
        ...
70    0.500000
71    0.224490
72    1.245283
73    0.000000
74    0.000000
Length: 75, dtype: float64

In [ ]:
df['engagement'] = df['num_comments'] / (df['score'] + 1)
df

,post_id,category,author,num_comments,score,title,collected_at,engagement
0,47620933,technology,notem,36.0,59,Memo:Alanguagethatremembersonlythelast12lineso...,2026-04-09 11:38:49,0.600000
1,47624645,technology,franze,157.0,738,ShowHN:Apfel–ThefreeAIalreadyonyourMac,2026-04-09 11:38:49,0.212449
2,47627217,science,romes,127.0,218,Runningoutofdiskspaceinproduction,2026-04-09 11:38:49,0.579909
3,47627419,worldnews,cmitsakis,12.0,47,TheAxiossupplychainattackusedindividuallytarge...,2026-04-09 11:38:49,0.250000
4,47629485,science,thejash,54.0,67,Acasestudyintestingwith100+Claudeagentsinparallel,2026-04-09 11:38:49,0.794118
...,...,...,...,...,...,...,...,...
70,47699105,technology,airobus,3.0,5,ShowHN:ImagetoMusicAI–TurnAnyPhotointoanOrigin...,2026-04-09 11:38:49,0.500000
71,47699814,technology,ankitg12,11.0,48,ProcessManagerforAutonomousAIAgents,2026-04-09 11:38:49,0.224490
72,47700460,technology,meander_water,66.0,52,AskHN:Whatareyoubuildingthat'snotAIrelated?,2026-04-09 11:38:49,1.245283
73,47701013,technology,doener,0.0,9,LargestDutchpensionfundcutstieswithcontroversi...,2026-04-09 11:38:49,0.000000
74,47701971,technology,gpi,0.0,4,AIandremoteworkisadisasterforjuniorsoftwareeng...,2026-04-09 11:38:49,0.000000

In [ ]:

df['is_popular'] = df['score'] > df['score'].mean()
df

,post_id,category,author,num_comments,score,title,collected_at,engagement,is_popular
0,47620933,technology,notem,36.0,59,Memo:Alanguagethatremembersonlythelast12lineso...,2026-04-09 11:38:49,0.600000,False
1,47624645,technology,franze,157.0,738,ShowHN:Apfel–ThefreeAIalreadyonyourMac,2026-04-09 11:38:49,0.212449,True
2,47627217,science,romes,127.0,218,Runningoutofdiskspaceinproduction,2026-04-09 11:38:49,0.579909,True
3,47627419,worldnews,cmitsakis,12.0,47,TheAxiossupplychainattackusedindividuallytarge...,2026-04-09 11:38:49,0.250000,False
4,47629485,science,thejash,54.0,67,Acasestudyintestingwith100+Claudeagentsinparallel,2026-04-09 11:38:49,0.794118,False
...,...,...,...,...,...,...,...,...,...
70,47699105,technology,airobus,3.0,5,ShowHN:ImagetoMusicAI–TurnAnyPhotointoanOrigin...,2026-04-09 11:38:49,0.500000,False
71,47699814,technology,ankitg12,11.0,48,ProcessManagerforAutonomousAIAgents,2026-04-09 11:38:49,0.224490,False
72,47700460,technology,meander_water,66.0,52,AskHN:Whatareyoubuildingthat'snotAIrelated?,2026-04-09 11:38:49,1.245283,False
73,47701013,technology,doener,0.0,9,LargestDutchpensionfundcutstieswithcontroversi...,2026-04-09 11:38:49,0.000000,False
74,47701971,technology,gpi,0.0,4,AIandremoteworkisadisasterforjuniorsoftwareeng...,2026-04-09 11:38:49,0.000000,False

Saving the updated DataFrame (with the 2 new columns) to data/trends_analysed.csv

In [ ]:
df.to_csv('data/trends_analysed.csv')

In [ ]:
print(f"Loaded data: {shape}","\n\n",
      "First 5 rows","\n",
      f"{head}","\n\n",
      "Average score:","\n\n",
      f"{x}","\n\n",
      "Most stories in: ",f"technology ({len(df_high[df_high['category'] == 'technology'])})",
      "\n\n",
      "Most Commented story: ",f"{mcomm}- {num}","\n\n"
      "Saved to data/trends_analysed.csv"
)

Loaded data: (75, 7)

 First 5 rows
     post_id    category     author  num_comments  score  \
0  47620933  technology      notem          36.0     59
1  47624645  technology     franze         157.0    738
2  47627217     science      romes         127.0    218
3  47627419   worldnews  cmitsakis          12.0     47
4  47629485     science    thejash          54.0     67

                                               title         collected_at
0  Memo:Alanguagethatremembersonlythelast12lineso...  2026-04-09 11:38:49
1             ShowHN:Apfel–ThefreeAIalreadyonyourMac  2026-04-09 11:38:49
2                  Runningoutofdiskspaceinproduction  2026-04-09 11:38:49
3  TheAxiossupplychainattackusedindividuallytarge...  2026-04-09 11:38:49
4  Acasestudyintestingwith100+Claudeagentsinparallel  2026-04-09 11:38:49

 Average score:

       Parameter         Avg
0         score  195.560000
1  num_comments   79.626667

 Most stories in:  technology (60)

 Most Commented story:  ProjectGlasswing:Securingcriticalsoftwareforthe...- 804.0

Saved to data/trends_analysed.csv