<a href="https://colab.research.google.com/github/HarryAI-6748/trendpulse-Harkirat/blob/main/task3_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the required libraries for data processing

In [1]:
import requests
import json
import pandas as pd

Fetching the data from REST API url and parsing the data into json followed by conversion to data frame

In [2]:
url = "https://restcountries.com/v3.1/all"
params = {"fields": "name,population,region,area,languages,borders,unMember,independent,subregion,continents"}

response = requests.get(url, params)
count_data = response.json()
df = pd.DataFrame(count_data)
df['common_name'] = df['name'].apply(lambda x: x['common'])
df['official_name'] = df['name'].apply(lambda x: x['official'])
df['languages'] = df['languages'].apply(lambda x: ', '.join(sorted(x.values())))
df['continents'] = df['continents'].str.join(', ')
df['borders'] = df['borders'].str.join(', ')

df

,name,languages,independent,unMember,region,subregion,borders,area,population,continents,common_name,official_name
0,"{'common': 'Ivory Coast', 'official': 'Republi...",French,True,True,Africa,Western Africa,"BFA, GHA, GIN, LBR, MLI",322463.0,31719275,Africa,Ivory Coast,Republic of Côte d'Ivoire
1,"{'common': 'Italy', 'official': 'Italian Repub...","Catalan, Italian",True,True,Europe,Southern Europe,"AUT, FRA, SMR, SVN, CHE, VAT",301336.0,58927633,Europe,Italy,Italian Republic
2,"{'common': 'Kyrgyzstan', 'official': 'Kyrgyz R...","Kyrgyz, Russian",True,True,Asia,Central Asia,"CHN, KAZ, TJK, UZB",199951.0,7281800,Asia,Kyrgyzstan,Kyrgyz Republic
3,"{'common': 'Papua New Guinea', 'official': 'In...","English, Hiri Motu, Tok Pisin",True,True,Oceania,Melanesia,IDN,462840.0,11781559,Oceania,Papua New Guinea,Independent State of Papua New Guinea
4,"{'common': 'Fiji', 'official': 'Republic of Fi...","English, Fiji Hindi, Fijian",True,True,Oceania,Melanesia,,18272.0,900869,Oceania,Fiji,Republic of Fiji
...,...,...,...,...,...,...,...,...,...,...,...,...
245,"{'common': 'Singapore', 'official': 'Republic ...","Chinese, English, Malay, Tamil",True,True,Asia,South-Eastern Asia,,710.0,6110200,Asia,Singapore,Republic of Singapore
246,"{'common': 'Costa Rica', 'official': 'Republic...",Spanish,True,True,Americas,Central America,"NIC, PAN",51100.0,5309625,North America,Costa Rica,Republic of Costa Rica
247,"{'common': 'Serbia', 'official': 'Republic of ...",Serbian,True,True,Europe,Southeast Europe,"BIH, BGR, HRV, HUN, UNK, MKD, MNE, ROU",77589.0,6567783,Europe,Serbia,Republic of Serbia
248,"{'common': 'Poland', 'official': 'Republic of ...",Polish,True,True,Europe,Central Europe,"BLR, CZE, DEU, LTU, RUS, SVK, UKR",312679.0,37392000,Europe,Poland,Republic of Poland
249,"{'common': 'Jordan', 'official': 'Hashemite Ki...",Arabic,True,True,Asia,Western Asia,"IRQ, ISR, PSE, SAU, SYR",89342.0,11734000,Asia,Jordan,Hashemite Kingdom of Jordan

Re-arranging the columns for better data corelation and analysis

In [3]:
df.drop(columns = ['name'], inplace = True)
df = df[['common_name', 'continents', 'region', 'subregion','independent','unMember','languages','area','population','borders']]
df

,common_name,continents,region,subregion,independent,unMember,languages,area,population,borders
0,Ivory Coast,Africa,Africa,Western Africa,True,True,French,322463.0,31719275,"BFA, GHA, GIN, LBR, MLI"
1,Italy,Europe,Europe,Southern Europe,True,True,"Catalan, Italian",301336.0,58927633,"AUT, FRA, SMR, SVN, CHE, VAT"
2,Kyrgyzstan,Asia,Asia,Central Asia,True,True,"Kyrgyz, Russian",199951.0,7281800,"CHN, KAZ, TJK, UZB"
3,Papua New Guinea,Oceania,Oceania,Melanesia,True,True,"English, Hiri Motu, Tok Pisin",462840.0,11781559,IDN
4,Fiji,Oceania,Oceania,Melanesia,True,True,"English, Fiji Hindi, Fijian",18272.0,900869,
...,...,...,...,...,...,...,...,...,...,...
245,Singapore,Asia,Asia,South-Eastern Asia,True,True,"Chinese, English, Malay, Tamil",710.0,6110200,
246,Costa Rica,North America,Americas,Central America,True,True,Spanish,51100.0,5309625,"NIC, PAN"
247,Serbia,Europe,Europe,Southeast Europe,True,True,Serbian,77589.0,6567783,"BIH, BGR, HRV, HUN, UNK, MKD, MNE, ROU"
248,Poland,Europe,Europe,Central Europe,True,True,Polish,312679.0,37392000,"BLR, CZE, DEU, LTU, RUS, SVK, UKR"
249,Jordan,Asia,Asia,Western Asia,True,True,Arabic,89342.0,11734000,"IRQ, ISR, PSE, SAU, SYR"

Total Number of countries per continent

In [4]:
con_df = df.groupby('continents')['common_name'].count().rename('Total_countries').sort_values( ascending=False).reset_index()
con_df

      continents  Total_countries
0         Africa               58
1         Europe               52
2           Asia               50
3  North America               41
4        Oceania               27
5  South America               14
6     Antarctica                5
7   Europe, Asia                3

Total Number of countries per region

In [5]:
Tot_df = df.groupby('region')['common_name'].count().rename('Total_countries').sort_values(ascending=False).reset_index()
Tot_df

      region  Total_countries
0     Africa               59
1   Americas               56
2     Europe               53
3       Asia               50
4    Oceania               27
5  Antarctic                5

Total Number of countries per subregion

In [6]:
df.groupby('subregion')['common_name'].count().rename('Total_countries').sort_values(ascending=False).reset_index()

                    subregion  Total_countries
0                   Caribbean               28
1              Eastern Africa               19
2              Western Africa               17
3                Western Asia               17
4             Northern Europe               16
5               South America               14
6          South-Eastern Asia               11
7             Southern Europe               10
8               Middle Africa               10
9                   Polynesia               10
10           Southeast Europe                9
11              Southern Asia                9
12             Western Europe                8
13               Eastern Asia                8
14            Central America                7
15              North America                7
16                 Micronesia                7
17            Northern Africa                7
18             Central Europe                6
19            Southern Africa                6
20                                           5
21  Australia and New Zealand                5
22               Central Asia                5
23                  Melanesia                5
24             Eastern Europe                4

Number of sub-regions per continent

In [7]:
df.groupby('continents')['subregion'].count().sort_values(ascending=False).reset_index()

      continents  subregion
0         Africa         58
1         Europe         52
2           Asia         50
3  North America         41
4        Oceania         27
5  South America         14
6     Antarctica          5
7   Europe, Asia          3

Total number of non-independent countries

In [8]:
dx = df[df['independent'] == False]
dx['independent'].count()
#dx

np.int64(55)

Total number of independent countries

In [9]:
dx = df[df['independent'] == True]
dx['independent'].count()

np.int64(195)

Number of independent countries per region

In [10]:
ind_df = df.groupby('region')['independent'].sum().rename('Independent_countries').sort_values(ascending=False).reset_index()
ind_df

      region  Independent_countries
0     Africa                     54
1       Asia                     46
2     Europe                     46
3   Americas                     35
4    Oceania                     14
5  Antarctic                      0

Total number of non-independent countries per region

In [11]:
df_merged = pd.merge(Tot_df, ind_df, on='region')
df_merged['Non_independent_countries'] = df_merged['Total_countries'] - df_merged['Independent_countries']
df_merged.sort_values(by='Non_independent_countries', ascending=False)

,region,Total_countries,Independent_countries,Non_independent_countries
1,Americas,56,35,21
4,Oceania,27,14,13
2,Europe,53,46,7
0,Africa,59,54,5
5,Antarctic,5,0,5
3,Asia,50,46,4

Number of UN members per continent

In [12]:
un_df = df.groupby('continents')['unMember'].sum().rename('Total_UN_members').sort_values(ascending=False).reset_index()
un_df

      continents  Total_UN_members
0         Africa                53
1           Asia                43
2         Europe                43
3  North America                23
4        Oceania                15
5  South America                12
6   Europe, Asia                 3
7     Antarctica                 0

In [13]:
df_merged_1 = pd.merge(con_df, un_df, on='continents')
df_merged_1['Non_UN_members'] = df_merged_1['Total_countries'] - df_merged_1['Total_UN_members']
df_merged_1.sort_values(by='Non_UN_members', ascending=False)

      continents  Total_countries  Total_UN_members  Non_UN_members
3  North America               41                23              18
4        Oceania               27                15              12
1         Europe               52                43               9
2           Asia               50                43               7
0         Africa               58                53               5
6     Antarctica                5                 0               5
5  South America               14                12               2
7   Europe, Asia                3                 3               0

Number of UN members per region

In [14]:
un_df_1 = df.groupby('region')['unMember'].sum().rename('Tot_reg_UN_members').sort_values(ascending=False).reset_index()
un_df_1

      region  Tot_reg_UN_members
0     Africa                  53
1       Asia                  46
2     Europe                  44
3   Americas                  35
4    Oceania                  14
5  Antarctic                   0

In [15]:
df_merged_2 = pd.merge(Tot_df, un_df_1, on='region')
df_merged_2['Non_reg_UN_members'] = df_merged_2['Total_countries'] - df_merged_2['Tot_reg_UN_members']
df_merged_2.sort_values(by='Non_reg_UN_members', ascending=False)

      region  Total_countries  Tot_reg_UN_members  Non_reg_UN_members
1   Americas               56                  35                  21
4    Oceania               27                  14                  13
2     Europe               53                  44                   9
0     Africa               59                  53                   6
5  Antarctic                5                   0                   5
3       Asia               50                  46                   4

Number of independent countries which are part of UN

In [16]:
df['independent_UN'] = df['independent'] & df['unMember']
df[df['independent_UN']]
df[df['independent_UN']]['common_name'].count()
#

np.int64(192)

most spoken languages across world

In [17]:
df['languages'].str.split(', ').explode().value_counts().reset_index()
#

      languages  count
0       English     91
1        French     46
2        Arabic     25
3       Spanish     24
4    Portuguese     10
..          ...    ...
151  Belarusian      1
152     Faroese      1
153   Hungarian      1
154    Tigrinya      1
155      Polish      1

[156 rows x 2 columns]

Country with max area

In [18]:
df[df['area'] == df['area'].max()]['common_name'].reset_index()['common_name'][0]

'Russia'

Country with minimum area

In [19]:
df[df['area'] == df['area'].min()]['common_name'].reset_index()['common_name'][0]

'Vatican City'

Subregion with max area

In [20]:
df.groupby('subregion')['area'].sum().sort_values(ascending=False).reset_index()['subregion'][0]

'North America'

Subregion with minimum area

In [21]:
df.groupby('subregion')['area'].sum().sort_values(ascending=True).reset_index()['subregion'][0]

'Micronesia'

Country with maximum population

In [22]:
df[df['population'] == df['population'].max()]['common_name'].reset_index()['common_name'][0]

'India'

Country with minimum population

In [23]:
df[df['population'] == df['population'].min()]['common_name'].reset_index()['common_name'][0]

'Heard Island and McDonald Islands'

Subregion with maximum population

In [25]:
df.groupby('subregion')['population'].sum().sort_values(ascending=False).reset_index()['subregion'][0]

'Southern Asia'

Subregion with minimum population

In [26]:
x = df.groupby('subregion')['population'].sum().sort_values(ascending=True).reset_index()['subregion'][0]
x + 'Antarctic'

'Antarctic'

Region with maximum population

In [27]:
df.groupby('region')['population'].sum().sort_values(ascending=False).reset_index()['region'][0]

'Asia'

Region with minimum population

In [28]:
df.groupby('region')['population'].sum().sort_values(ascending=True).reset_index()['region'][0]

'Antarctic'

Total number of non independent population

In [31]:
print(df[~df['independent']]['population'].sum())

45064147

Total number of independent population

In [32]:
print(df[df['independent']]['population'].sum())

7974431313

Ratio of Population and Area

Ratio of Population and Area - country wise

In [33]:
df['population_area_ratio'] = df['population'] / df['area']
df.sort_values(by='population_area_ratio', ascending=False)[['common_name','population','area','population_area_ratio']].reset_index().drop(columns='index').head(50)

,common_name,population,area,population_area_ratio
0,Macau,685900,30.00,22863.333333
1,Monaco,38423,2.02,19021.287129
2,Singapore,6110200,710.00,8605.915493
3,Hong Kong,7527500,1104.00,6818.387681
4,Gibraltar,38000,6.00,6333.333333
5,Bahrain,1594654,765.00,2084.515033
6,Malta,574250,316.00,1817.246835
7,Vatican City,882,0.49,1800.000000
8,Maldives,515132,300.00,1717.106667
9,Sint Maarten,41349,34.00,1216.147059
10,Bermuda,64055,54.00,1186.203704
11,Bangladesh,169828911,147570.00,1150.836288
12,Jersey,103267,116.00,890.232759
13,Palestine,5483450,6220.00,881.583601
14,Mayotte,320901,374.00,858.024064
15,Guernsey,64781,78.00,830.525641
16,Taiwan,23317031,36197.00,644.170263
17,Barbados,267800,430.00,622.790698
18,Mauritius,1243741,2040.00,609.676961
19,Aruba,107566,180.00,597.588889
20,Saint Martin,31496,53.00,594.264151
21,San Marino,34132,61.00,559.540984
22,Nauru,11680,21.00,556.190476
23,Rwanda,14104969,26338.00,535.536829
24,Lebanon,5490000,10452.00,525.258324
25,South Korea,51159889,100210.00,510.526784
26,Saint Barthélemy,10562,21.00,502.952381
27,Comoros,919901,1862.00,494.039205
28,Israel,10134800,21937.00,461.995715
29,Burundi,12332788,27834.00,443.083567
30,Netherlands,18100436,41865.00,432.352466
31,India,1417492000,3287263.00,431.207360
32,Haiti,11867032,27750.00,427.640793
33,Tuvalu,10643,26.00,409.346154
34,Belgium,11825551,30528.00,387.367368
35,Puerto Rico,3203295,8870.00,361.138106
36,Réunion,896175,2511.00,356.899642
37,Curaçao,156115,444.00,351.610360
38,Philippines,114123600,342353.00,333.350664
39,Sri Lanka,21763170,65610.00,331.705075
40,Japan,123210000,377930.00,326.012754
41,Cayman Islands,84738,264.00,320.977273
42,Grenada,109021,344.00,316.921512
43,Martinique,349925,1128.00,310.217199
44,Vietnam,101343800,331212.00,305.978648
45,Pakistan,241499431,796095.00,303.355041
46,Saint Lucia,184100,616.00,298.863636
47,El Salvador,6029976,21041.00,286.582197
48,Saint Vincent and the Grenadines,110872,389.00,285.017995
49,United Kingdom,69281437,244376.00,283.503441

Ratio of Population and Area - Continent wise

In [34]:
df_p = df.groupby('continents')['population'].sum().reset_index()# /
#k
df_a = df.groupby('continents')['area'].sum().reset_index()#.rename('population_cont_area_ratio').reset_index()
#l
n = pd.merge(df_p,df_a,on='continents')
n['population_cont_area_ratio'] = n['population'] / n['area']
n
n.sort_values(by='population_cont_area_ratio', ascending=False).reset_index().drop(columns='index')

      continents  population         area  population_cont_area_ratio
0           Asia  4627436364  31168341.00                  148.465918
1         Europe   595629597   6031491.51                   98.753284
2         Africa  1462464411  30320573.00                   48.233403
3  North America   605528754  24396963.00                   24.819841
4  South America   437051029  17833382.00                   24.507467
5   Europe, Asia   241934991  17968408.00                   13.464464
6        Oceania    49448614   8528443.20                    5.798082
7     Antarctica        1700  14012111.00                    0.000121